spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 424984163476-c49eb588d7pu56g5bs5ldaechkhdqneh.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email,https://www.googleapis.com/auth/drive.file ,https://www.googleapis.com/auth/drive.metadata.readonly
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
