spring.application.name=nfc-api

# Application
application.name = Tag4Ever
application.jwt.name = Tag4EverJWT

# Server Configuration
server.port=8080

# Google Drive Configuration
google.drive.api.url = ${GOOGLE_DRIVE_API_URL:https://www.googleapis.com/drive/v3/files?q='%s'+in+parents+and+trashed=false&fields=files(id,name,webViewLink,mimeType)&key=%s}
google.drive.api.key=${GOOGLE_DRIVE_API_KEY:AIzaSyBRcZZp1ydJ3sbUS0lWo28mnKMJAIePNkk}

# Google OAuth Configuration
google.client.id=${GOOGLE_CLIENT_ID:424984163476-c49eb588d7pu56g5bs5ldaechkhdqneh.apps.googleusercontent.com}
google.client.secret=${GOOGLE_CLIENT_SECRET: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}
google.redirect.uri=${GOOGLE_REDIRECT_URI:http://localhost:5173/auth/callback}
#google.redirect.uri=${GOOGLE_REDIRECT_URI:https://jewelinkry.com/auth/callback}

# JWT Configuration
jwt.secret=${JWT_SECRET:superSecretKeysssuperSecretKeysssuperSecretKeysssuperSecretKeyss}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# Maksimum dosya boyutu (örnek: 20MB)
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB

# Database Configuration (Postgres)
spring.datasource.url=jdbc:postgresql://191.101.81.228:5432/salchatech
spring.datasource.username=salih
spring.datasource.password=SCokr1913.1914.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.salcatech.nfc_api=DEBUG
logging.level.org.springframework.security=DEBUG
