spring.application.name=nfc-api

# JWT
jwt.expiration-ms=3600000

# CORS
cors.allowed.origins=http://localhost:3000,http://localhost:5173,http://localhost:8080
cors.allowed.methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed.headers=*

# JPA Config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.salcatech.nfc_api=DEBUG
logging.level.org.springframework.security=DEBUG

# SSL
server.ssl.enabled=${SERVER_SSL_ENABLED:true}
server.ssl.key-store=/app/config/application-pem.p12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.port=8443
